api_platform:
    title: Knowledge Platform API
    version: 1.0.0
    eager_loading:
        max_joins: 30
        fetch_partial: true
        force_eager: false
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_items_per_page: 30
        normalization_context:
            enable_max_depth: true
            groups: ['read']

    swagger:
        api_keys:
            bearerAuth:
                name: Authorization
                type: header