api_platform:
    title: Hello API Platform
    version: 1.0.0
    eager_loading:
        max_joins: 100
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    swagger:
        api_keys:
            bearerAuth:
                name: Authorization
                type: header