vich_uploader:
    db_driver: orm
    mappings:
        lesson_video:
            uri_prefix: /uploads/videos
            upload_destination: '%kernel.project_dir%/public/uploads/videos'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true
        img:
            uri_prefix: /uploads/img
            upload_destination: '%kernel.project_dir%/public/uploads/img'