controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Route pour servir les fichiers uploadés
uploads:
    path: /uploads/{path}
    controller: App\Controller\UploadController::serve
    requirements:
        path: .*
